version: "3"
services:
  app:
    container_name: Realworld-nft-marketplace
    restart: unless-stopped
    build: .
    ports:
      - "4204:4200"
    environment:
      SHELL: /bin/bash
      NODE_ENV: local
    volumes:
      - './:/app'
      - '/app/node_modules'
    entrypoint: ng serve --host 0.0.0.0