export const COUNTRIES = [
  { name: 'Afghanistan', dialCode: '+93', flag: '🇦🇫', regionCode: 'AF' },
  { name: 'Åland Islands', dialCode: '+358', flag: '🇦🇽', regionCode: 'AX' },
  { name: 'Albania', dialCode: '+355', flag: '🇦🇱', regionCode: 'AL' },
  { name: 'Algeria', dialCode: '+213', flag: '🇩🇿', regionCode: 'DZ' },
  { name: 'American Samoa', dialCode: '+1', flag: '🇦🇸', regionCode: 'AS' },
  { name: 'Andorra', dialCode: '+376', flag: '🇦🇩', regionCode: 'AD' },
  { name: 'Angola', dialCode: '+244', flag: '🇦🇴', regionCode: 'AO' },
  { name: 'Anguilla', dialCode: '+1', flag: '🇦🇮', regionCode: 'AI' },
  { name: 'Antarctica', dialCode: '+672', flag: '🇦🇶', regionCode: 'AQ' },
  { name: 'Antigua and Barbuda', dialCode: '+1', flag: '🇦🇬', regionCode: 'AG' },
  { name: 'Argentina', dialCode: '+54', flag: '🇦🇷', regionCode: 'AR' },
  { name: 'Armenia', dialCode: '+374', flag: '🇦🇲', regionCode: 'AM' },
  { name: 'Aruba', dialCode: '+297', flag: '🇦🇼', regionCode: 'AW' },
  { name: 'Australia', dialCode: '+61', flag: '🇦🇺', regionCode: 'AU' },
  { name: 'Austria', dialCode: '+43', flag: '🇦🇹', regionCode: 'AT' },
  { name: 'Azerbaijan', dialCode: '+994', flag: '🇦🇿', regionCode: 'AZ' },
  { name: 'Bahamas', dialCode: '+1', flag: '🇧🇸', regionCode: 'BS' },
  { name: 'Bahrain', dialCode: '+973', flag: '🇧🇭', regionCode: 'BH' },
  { name: 'Bangladesh', dialCode: '+880', flag: '🇧🇩', regionCode: 'BD' },
  { name: 'Barbados', dialCode: '+1', flag: '🇧🇧', regionCode: 'BB' },
  { name: 'Belarus', dialCode: '+375', flag: '🇧🇾', regionCode: 'BY' },
  { name: 'Belgium', dialCode: '+32', flag: '🇧🇪', regionCode: 'BE' },
  { name: 'Belize', dialCode: '+501', flag: '🇧🇿', regionCode: 'BZ' },
  { name: 'Benin', dialCode: '+229', flag: '🇧🇯', regionCode: 'BJ' },
  { name: 'Bermuda', dialCode: '+1', flag: '🇧🇲', regionCode: 'BM' },
  { name: 'Bhutan', dialCode: '+975', flag: '🇧🇹', regionCode: 'BT' },
  { name: 'Bolivia', dialCode: '+591', flag: '🇧🇴', regionCode: 'BO' },
  { name: 'Bonaire, Sint Eustatius and Saba', dialCode: '+599', flag: '🇧🇶', regionCode: 'BQ' },
  { name: 'Bosnia and Herzegovina', dialCode: '+387', flag: '🇧🇦', regionCode: 'BA' },
  { name: 'Botswana', dialCode: '+267', flag: '🇧🇼', regionCode: 'BW' },
  { name: 'Bouvet Island', dialCode: '+47', flag: '🇧🇻', regionCode: 'BV' },
  { name: 'Brazil', dialCode: '+55', flag: '🇧🇷', regionCode: 'BR' },
  { name: 'British Indian Ocean Territory', dialCode: '+246', flag: '🇮🇴', regionCode: 'IO' },
  { name: 'Brunei Darussalam', dialCode: '+673', flag: '🇧🇳', regionCode: 'BN' },
  { name: 'Bulgaria', dialCode: '+359', flag: '🇧🇬', regionCode: 'BG' },
  { name: 'Burkina Faso', dialCode: '+226', flag: '🇧🇫', regionCode: 'BF' },
  { name: 'Burundi', dialCode: '+257', flag: '🇧🇮', regionCode: 'BI' },
  { name: 'Cambodia', dialCode: '+855', flag: '🇰🇭', regionCode: 'KH' },
  { name: 'Cameroon', dialCode: '+237', flag: '🇨🇲', regionCode: 'CM' },
  { name: 'Canada', dialCode: '+1', flag: '🇨🇦', regionCode: 'CA' },
  { name: 'Cape Verde', dialCode: '+238', flag: '🇨🇻', regionCode: 'CV' },
  { name: 'Cayman Islands', dialCode: '+1', flag: '🇰🇾', regionCode: 'KY' },
  { name: 'Central African Republic', dialCode: '+236', flag: '🇨🇫', regionCode: 'CF' },
  { name: 'Chad', dialCode: '+235', flag: '🇹🇩', regionCode: 'TD' },
  { name: 'Chile', dialCode: '+56', flag: '🇨🇱', regionCode: 'CL' },
  { name: 'China', dialCode: '+86', flag: '🇨🇳', regionCode: 'CN' },
  { name: 'Christmas Island', dialCode: '+61', flag: '🇨🇽', regionCode: 'CX' },
  { name: 'Cocos (Keeling) Islands', dialCode: '+61', flag: '🇨🇨', regionCode: 'CC' },
  { name: 'Colombia', dialCode: '+57', flag: '🇨🇴', regionCode: 'CO' },
  { name: 'Comoros', dialCode: '+269', flag: '🇰🇲', regionCode: 'KM' },
  { name: 'Congo', dialCode: '+242', flag: '🇨🇬', regionCode: 'CG' },
  { name: 'Congo, Democratic Republic of the Congo', dialCode: '+243', flag: '🇨🇩', regionCode: 'CD' },
  { name: 'Cook Islands', dialCode: '+682', flag: '🇨🇰', regionCode: 'CK' },
  { name: 'Costa Rica', dialCode: '+506', flag: '🇨🇷', regionCode: 'CR' },
  { name: 'Cote D\'Ivoire', dialCode: '+225', flag: '🇨🇮', regionCode: 'CI' },
  { name: 'Croatia', dialCode: '+385', flag: '🇭🇷', regionCode: 'HR' },
  { name: 'Cuba', dialCode: '+53', flag: '🇨🇺', regionCode: 'CU' },
  { name: 'Curaçao', dialCode: '+599', flag: '🇨🇼', regionCode: 'CW' },
  { name: 'Cyprus', dialCode: '+357', flag: '🇨🇾', regionCode: 'CY' },
  { name: 'Czech Republic', dialCode: '+420', flag: '🇨🇿', regionCode: 'CZ' },
  { name: 'Denmark', dialCode: '+45', flag: '🇩🇰', regionCode: 'DK' },
  { name: 'Djibouti', dialCode: '+253', flag: '🇩🇯', regionCode: 'DJ' },
  { name: 'Dominica', dialCode: '+1', flag: '🇩🇲', regionCode: 'DM' },
  { name: 'Dominican Republic', dialCode: '+1', flag: '🇩🇴', regionCode: 'DO' },
  { name: 'Ecuador', dialCode: '+593', flag: '🇪🇨', regionCode: 'EC' },
  { name: 'Egypt', dialCode: '+20', flag: '🇪🇬', regionCode: 'EG' },
  { name: 'El Salvador', dialCode: '+503', flag: '🇸🇻', regionCode: 'SV' },
  { name: 'Equatorial Guinea', dialCode: '+240', flag: '🇬🇶', regionCode: 'GQ' },
  { name: 'Eritrea', dialCode: '+291', flag: '🇪🇷', regionCode: 'ER' },
  { name: 'Estonia', dialCode: '+372', flag: '🇪🇪', regionCode: 'EE' },
  { name: 'Ethiopia', dialCode: '+251', flag: '🇪🇹', regionCode: 'ET' },
  { name: 'Falkland Islands (Malvinas)', dialCode: '+500', flag: '🇫🇰', regionCode: 'FK' },
  { name: 'Faroe Islands', dialCode: '+298', flag: '🇫🇴', regionCode: 'FO' },
  { name: 'Fiji', dialCode: '+679', flag: '🇫🇯', regionCode: 'FJ' },
  { name: 'Finland', dialCode: '+358', flag: '🇫🇮', regionCode: 'FI' },
  { name: 'France', dialCode: '+33', flag: '🇫🇷', regionCode: 'FR' },
  { name: 'French Guiana', dialCode: '+594', flag: '🇬🇫', regionCode: 'GF' },
  { name: 'French Polynesia', dialCode: '+689', flag: '🇵🇫', regionCode: 'PF' },
  { name: 'French Southern Territories', dialCode: '+262', flag: '🇹🇫', regionCode: 'TF' },
  { name: 'Gabon', dialCode: '+241', flag: '🇬🇦', regionCode: 'GA' },
  { name: 'Gambia', dialCode: '+220', flag: '🇬🇲', regionCode: 'GM' },
  { name: 'Georgia', dialCode: '+995', flag: '🇬🇪', regionCode: 'GE' },
  { name: 'Germany', dialCode: '+49', flag: '🇩🇪', regionCode: 'DE' },
  { name: 'Ghana', dialCode: '+233', flag: '🇬🇭', regionCode: 'GH' },
  { name: 'Gibraltar', dialCode: '+350', flag: '🇬🇮', regionCode: 'GI' },
  { name: 'Greece', dialCode: '+30', flag: '🇬🇷', regionCode: 'GR' },
  { name: 'Greenland', dialCode: '+299', flag: '🇬🇱', regionCode: 'GL' },
  { name: 'Grenada', dialCode: '+1', flag: '🇬🇩', regionCode: 'GD' },
  { name: 'Guadeloupe', dialCode: '+590', flag: '🇬🇵', regionCode: 'GP' },
  { name: 'Guam', dialCode: '+1', flag: '🇬🇺', regionCode: 'GU' },
  { name: 'Guatemala', dialCode: '+502', flag: '🇬🇹', regionCode: 'GT' },
  { name: 'Guernsey', dialCode: '+44', flag: '🇬🇬', regionCode: 'GG' },
  { name: 'Guinea', dialCode: '+224', flag: '🇬🇳', regionCode: 'GN' },
  { name: 'Guinea-Bissau', dialCode: '+245', flag: '🇬🇼', regionCode: 'GW' },
  { name: 'Guyana', dialCode: '+592', flag: '🇬🇾', regionCode: 'GY' },
  { name: 'Haiti', dialCode: '+509', flag: '🇭🇹', regionCode: 'HT' },
  { name: 'Heard Island and Mcdonald Islands', dialCode: '+672', flag: '🇭🇲', regionCode: 'HM' },
  { name: 'Holy See (Vatican City State)', dialCode: '+379', flag: '🇻🇦', regionCode: 'VA' },
  { name: 'Honduras', dialCode: '+504', flag: '🇭🇳', regionCode: 'HN' },
  { name: 'Hong Kong', dialCode: '+852', flag: '🇭🇰', regionCode: 'HK' },
  { name: 'Hungary', dialCode: '+36', flag: '🇭🇺', regionCode: 'HU' },
  { name: 'Iceland', dialCode: '+354', flag: '🇮🇸', regionCode: 'IS' },
  { name: 'India', dialCode: '+91', flag: '🇮🇳', regionCode: 'IN' },
  { name: 'Indonesia', dialCode: '+62', flag: '🇮🇩', regionCode: 'ID' },
  { name: 'Iran, Islamic Republic of Persian Gulf', dialCode: '+98', flag: '🇮🇷', regionCode: 'IR' },
  { name: 'Iraq', dialCode: '+964', flag: '🇮🇶', regionCode: 'IQ' },
  { name: 'Ireland', dialCode: '+353', flag: '🇮🇪', regionCode: 'IE' },
  { name: 'Isle of Man', dialCode: '+44', flag: '🇮🇲', regionCode: 'IM' },
  { name: 'Israel', dialCode: '+972', flag: '🇮🇱', regionCode: 'IL' },
  { name: 'Italy', dialCode: '+39', flag: '🇮🇹', regionCode: 'IT' },
  { name: 'Jamaica', dialCode: '+1', flag: '🇯🇲', regionCode: 'JM' },
  { name: 'Japan', dialCode: '+81', flag: '🇯🇵', regionCode: 'JP' },
  { name: 'Jersey', dialCode: '+44', flag: '🇯🇪', regionCode: 'JE' },
  { name: 'Jordan', dialCode: '+962', flag: '🇯🇴', regionCode: 'JO' },
  { name: 'Kazakhstan', dialCode: '+77', flag: '🇰🇿', regionCode: 'KZ' },
  { name: 'Kenya', dialCode: '+254', flag: '🇰🇪', regionCode: 'KE' },
  { name: 'Kiribati', dialCode: '+686', flag: '🇰🇮', regionCode: 'KI' },
  { name: 'Korea, Democratic People\'s Republic of Korea', dialCode: '+850', flag: '🇰🇵', regionCode: 'KP' },
  { name: 'Korea, Republic of South Korea', dialCode: '+82', flag: '🇰🇷', regionCode: 'KR' },
  { name: 'Kosovo', dialCode: '+383', flag: '🇽🇰', regionCode: 'XK' },
  { name: 'Kuwait', dialCode: '+965', flag: '🇰🇼', regionCode: 'KW' },
  { name: 'Kyrgyzstan', dialCode: '+996', flag: '🇰🇬', regionCode: 'KG' },
  { name: 'Laos', dialCode: '+856', flag: '🇱🇦', regionCode: 'LA' },
  { name: 'Latvia', dialCode: '+371', flag: '🇱🇻', regionCode: 'LV' },
  { name: 'Lebanon', dialCode: '+961', flag: '🇱🇧', regionCode: 'LB' },
  { name: 'Lesotho', dialCode: '+266', flag: '🇱🇸', regionCode: 'LS' },
  { name: 'Liberia', dialCode: '+231', flag: '🇱🇷', regionCode: 'LR' },
  { name: 'Libyan Arab Jamahiriya', dialCode: '+218', flag: '🇱🇾', regionCode: 'LY' },
  { name: 'Liechtenstein', dialCode: '+423', flag: '🇱🇮', regionCode: 'LI' },
  { name: 'Lithuania', dialCode: '+370', flag: '🇱🇹', regionCode: 'LT' },
  { name: 'Luxembourg', dialCode: '+352', flag: '🇱🇺', regionCode: 'LU' },
  { name: 'Macao', dialCode: '+853', flag: '🇲🇴', regionCode: 'MO' },
  { name: 'Macedonia', dialCode: '+389', flag: '🇲🇰', regionCode: 'MK' },
  { name: 'Madagascar', dialCode: '+261', flag: '🇲🇬', regionCode: 'MG' },
  { name: 'Malawi', dialCode: '+265', flag: '🇲🇼', regionCode: 'MW' },
  { name: 'Malaysia', dialCode: '+60', flag: '🇲🇾', regionCode: 'MY' },
  { name: 'Maldives', dialCode: '+960', flag: '🇲🇻', regionCode: 'MV' },
  { name: 'Mali', dialCode: '+223', flag: '🇲🇱', regionCode: 'ML' },
  { name: 'Malta', dialCode: '+356', flag: '🇲🇹', regionCode: 'MT' },
  { name: 'Marshall Islands', dialCode: '+692', flag: '🇲🇭', regionCode: 'MH' },
  { name: 'Martinique', dialCode: '+596', flag: '🇲🇶', regionCode: 'MQ' },
  { name: 'Mauritania', dialCode: '+222', flag: '🇲🇷', regionCode: 'MR' },
  { name: 'Mauritius', dialCode: '+230', flag: '🇲🇺', regionCode: 'MU' },
  { name: 'Mayotte', dialCode: '+262', flag: '🇾🇹', regionCode: 'YT' },
  { name: 'Mexico', dialCode: '+52', flag: '🇲🇽', regionCode: 'MX' },
  { name: 'Micronesia, Federated States of Micronesia', dialCode: '+691', flag: '🇫🇲', regionCode: 'FM' },
  { name: 'Moldova', dialCode: '+373', flag: '🇲🇩', regionCode: 'MD' },
  { name: 'Monaco', dialCode: '+377', flag: '🇲🇨', regionCode: 'MC' },
  { name: 'Mongolia', dialCode: '+976', flag: '🇲🇳', regionCode: 'MN' },
  { name: 'Montenegro', dialCode: '+382', flag: '🇲🇪', regionCode: 'ME' },
  { name: 'Montserrat', dialCode: '+1', flag: '🇲🇸', regionCode: 'MS' },
  { name: 'Morocco', dialCode: '+212', flag: '🇲🇦', regionCode: 'MA' },
  { name: 'Mozambique', dialCode: '+258', flag: '🇲🇿', regionCode: 'MZ' },
  { name: 'Myanmar', dialCode: '+95', flag: '🇲🇲', regionCode: 'MM' },
  { name: 'Namibia', dialCode: '+264', flag: '🇳🇦', regionCode: 'NA' },
  { name: 'Nauru', dialCode: '+674', flag: '🇳🇷', regionCode: 'NR' },
  { name: 'Nepal', dialCode: '+977', flag: '🇳🇵', regionCode: 'NP' },
  { name: 'Netherlands', dialCode: '+31', flag: '🇳🇱', regionCode: 'NL' },
  { name: 'Netherlands Antilles', dialCode: '+599', flag: '🇦🇳', regionCode: 'AN' },
  { name: 'New Caledonia', dialCode: '+687', flag: '🇳🇨', regionCode: 'NC' },
  { name: 'New Zealand', dialCode: '+64', flag: '🇳🇿', regionCode: 'NZ' },
  { name: 'Nicaragua', dialCode: '+505', flag: '🇳🇮', regionCode: 'NI' },
  { name: 'Niger', dialCode: '+227', flag: '🇳🇪', regionCode: 'NE' },
  { name: 'Nigeria', dialCode: '+234', flag: '🇳🇬', regionCode: 'NG' },
  { name: 'Niue', dialCode: '+683', flag: '🇳🇺', regionCode: 'NU' },
  { name: 'Norfolk Island', dialCode: '+672', flag: '🇳🇫', regionCode: 'NF' },
  { name: 'Northern Mariana Islands', dialCode: '+1', flag: '🇲🇵', regionCode: 'MP' },
  { name: 'Norway', dialCode: '+47', flag: '🇳🇴', regionCode: 'NO' },
  { name: 'Oman', dialCode: '+968', flag: '🇴🇲', regionCode: 'OM' },
  { name: 'Pakistan', dialCode: '+92', flag: '🇵🇰', regionCode: 'PK' },
  { name: 'Palau', dialCode: '+680', flag: '🇵🇼', regionCode: 'PW' },
  { name: 'Palestinian Territory, Occupied', dialCode: '+970', flag: '🇵🇸', regionCode: 'PS' },
  { name: 'Panama', dialCode: '+507', flag: '🇵🇦', regionCode: 'PA' },
  { name: 'Papua New Guinea', dialCode: '+675', flag: '🇵🇬', regionCode: 'PG' },
  { name: 'Paraguay', dialCode: '+595', flag: '🇵🇾', regionCode: 'PY' },
  { name: 'Peru', dialCode: '+51', flag: '🇵🇪', regionCode: 'PE' },
  { name: 'Philippines', dialCode: '+63', flag: '🇵🇭', regionCode: 'PH' },
  { name: 'Pitcairn', dialCode: '+872', flag: '🇵🇳', regionCode: 'PN' },
  { name: 'Poland', dialCode: '+48', flag: '🇵🇱', regionCode: 'PL' },
  { name: 'Portugal', dialCode: '+351', flag: '🇵🇹', regionCode: 'PT' },
  { name: 'Puerto Rico', dialCode: '+1', flag: '🇵🇷', regionCode: 'PR' },
  { name: 'Qatar', dialCode: '+974', flag: '🇶🇦', regionCode: 'QA' },
  { name: 'Romania', dialCode: '+40', flag: '🇷🇴', regionCode: 'RO' },
  { name: 'Russia', dialCode: '+7', flag: '🇷🇺', regionCode: 'RU' },
  { name: 'Rwanda', dialCode: '+250', flag: '🇷🇼', regionCode: 'RW' },
  { name: 'Reunion', dialCode: '+262', flag: '🇷🇪', regionCode: 'RE' },
  { name: 'Saint Barthelemy', dialCode: '+590', flag: '🇧🇱', regionCode: 'BL' },
  { name: 'Saint Helena, Ascension and Tristan Da Cunha', dialCode: '+290', flag: '🇸🇭', regionCode: 'SH' },
  { name: 'Saint Kitts and Nevis', dialCode: '+1', flag: '🇰🇳', regionCode: 'KN' },
  { name: 'Saint Lucia', dialCode: '+1', flag: '🇱🇨', regionCode: 'LC' },
  { name: 'Saint Martin', dialCode: '+590', flag: '🇲🇫', regionCode: 'MF' },
  { name: 'Saint Pierre and Miquelon', dialCode: '+508', flag: '🇵🇲', regionCode: 'PM' },
  { name: 'Saint Vincent and the Grenadines', dialCode: '+1', flag: '🇻🇨', regionCode: 'VC' },
  { name: 'Samoa', dialCode: '+685', flag: '🇼🇸', regionCode: 'WS' },
  { name: 'San Marino', dialCode: '+378', flag: '🇸🇲', regionCode: 'SM' },
  { name: 'Sao Tome and Principe', dialCode: '+239', flag: '🇸🇹', regionCode: 'ST' },
  { name: 'Saudi Arabia', dialCode: '+966', flag: '🇸🇦', regionCode: 'SA' },
  { name: 'Senegal', dialCode: '+221', flag: '🇸🇳', regionCode: 'SN' },
  { name: 'Serbia', dialCode: '+381', flag: '🇷🇸', regionCode: 'RS' },
  { name: 'Seychelles', dialCode: '+248', flag: '🇸🇨', regionCode: 'SC' },
  { name: 'Sierra Leone', dialCode: '+232', flag: '🇸🇱', regionCode: 'SL' },
  { name: 'Singapore', dialCode: '+65', flag: '🇸🇬', regionCode: 'SG' },
  { name: 'Slovakia', dialCode: '+421', flag: '🇸🇰', regionCode: 'SK' },
  { name: 'Slovenia', dialCode: '+386', flag: '🇸🇮', regionCode: 'SI' },
  { name: 'Solomon Islands', dialCode: '+677', flag: '🇸🇧', regionCode: 'SB' },
  { name: 'Somalia', dialCode: '+252', flag: '🇸🇴', regionCode: 'SO' },
  { name: 'South Africa', dialCode: '+27', flag: '🇿🇦', regionCode: 'ZA' },
  { name: 'South Sudan', dialCode: '+211', flag: '🇸🇸', regionCode: 'SS' },
  { name: 'Spain', dialCode: '+34', flag: '🇪🇸', regionCode: 'ES' },
  { name: 'Sri Lanka', dialCode: '+94', flag: '🇱🇰', regionCode: 'LK' },
  { name: 'Sudan', dialCode: '+249', flag: '🇸🇩', regionCode: 'SD' },
  { name: 'Suriname', dialCode: '+597', flag: '🇸🇷', regionCode: 'SR' },
  { name: 'Svalbard and Jan Mayen', dialCode: '+47', flag: '🇸🇯', regionCode: 'SJ' },
  { name: 'Swaziland', dialCode: '+268', flag: '🇸🇿', regionCode: 'SZ' },
  { name: 'Sweden', dialCode: '+46', flag: '🇸🇪', regionCode: 'SE' },
  { name: 'Switzerland', dialCode: '+41', flag: '🇨🇭', regionCode: 'CH' },
  { name: 'Syrian Arab Republic', dialCode: '+963', flag: '🇸🇾', regionCode: 'SY' },
  { name: 'Taiwan', dialCode: '+886', flag: '🇹🇼', regionCode: 'TW' },
  { name: 'Tajikistan', dialCode: '+992', flag: '🇹🇯', regionCode: 'TJ' },
  { name: 'Tanzania, United Republic of Tanzania', dialCode: '+255', flag: '🇹🇿', regionCode: 'TZ' },
  { name: 'Thailand', dialCode: '+66', flag: '🇹🇭', regionCode: 'TH' },
  { name: 'Timor-Leste', dialCode: '+670', flag: '🇹🇱', regionCode: 'TL' },
  { name: 'Togo', dialCode: '+228', flag: '🇹🇬', regionCode: 'TG' },
  { name: 'Tokelau', dialCode: '+690', flag: '🇹🇰', regionCode: 'TK' },
  { name: 'Tonga', dialCode: '+676', flag: '🇹🇴', regionCode: 'TO' },
  { name: 'Trinidad and Tobago', dialCode: '+1', flag: '🇹🇹', regionCode: 'TT' },
  { name: 'Tunisia', dialCode: '+216', flag: '🇹🇳', regionCode: 'TN' },
  { name: 'Turkey', dialCode: '+90', flag: '🇹🇷', regionCode: 'TR' },
  { name: 'Turkmenistan', dialCode: '+993', flag: '🇹🇲', regionCode: 'TM' },
  { name: 'Turks and Caicos Islands', dialCode: '+1', flag: '🇹🇨', regionCode: 'TC' },
  { name: 'Tuvalu', dialCode: '+688', flag: '🇹🇻', regionCode: 'TV' },
  { name: 'Uganda', dialCode: '+256', flag: '🇺🇬', regionCode: 'UG' },
  { name: 'Ukraine', dialCode: '+380', flag: '🇺🇦', regionCode: 'UA' },
  { name: 'United Arab Emirates', dialCode: '+971', flag: '🇦🇪', regionCode: 'AE' },
  { name: 'United Kingdom', dialCode: '+44', flag: '🇬🇧', regionCode: 'GB' },
  { name: 'United States', dialCode: '+1', flag: '🇺🇸', regionCode: 'US' },
  { name: 'Uruguay', dialCode: '+598', flag: '🇺🇾', regionCode: 'UY' },
  { name: 'Uzbekistan', dialCode: '+998', flag: '🇺🇿', regionCode: 'UZ' },
  { name: 'Vanuatu', dialCode: '+678', flag: '🇻🇺', regionCode: 'VU' },
  { name: 'Venezuela, Bolivarian Republic of Venezuela', dialCode: '+58', flag: '🇻🇪', regionCode: 'VE' },
  { name: 'Vietnam', dialCode: '+84', flag: '🇻🇳', regionCode: 'VN' },
  { name: 'Virgin Islands, British', dialCode: '+1', flag: '🇻🇬', regionCode: 'VG' },
  { name: 'Virgin Islands, U.S.', dialCode: '+1', flag: '🇻🇮', regionCode: 'VI' },
  { name: 'Wallis and Futuna', dialCode: '+681', flag: '🇼🇫', regionCode: 'WF' },
  { name: 'Yemen', dialCode: '+967', flag: '🇾🇪', regionCode: 'YE' },
  { name: 'Zambia', dialCode: '+260', flag: '🇿🇲', regionCode: 'ZM' },
  { name: 'Zimbabwe', dialCode: '+263', flag: '🇿🇼', regionCode: 'ZW' },
];
